// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJkMMJxoK286jgwPiXHyN4UUKbAM2neXA',
    appId: '1:359386672702:web:935230155de515a0f06b6f',
    messagingSenderId: '359386672702',
    projectId: 'challenger-app-c941b',
    authDomain: 'challenger-app-c941b.firebaseapp.com',
    storageBucket: 'challenger-app-c941b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVVcxxpl0RoSlok-ysgxbTOdzlxwGC1FI',
    appId: '1:359386672702:android:556408272e26405af06b6f',
    messagingSenderId: '359386672702',
    projectId: 'challenger-app-c941b',
    storageBucket: 'challenger-app-c941b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz0zU3DVLOLymMSQtVuRxKaCraEXWHJ-s',
    appId: '1:359386672702:ios:218397302235b8eaf06b6f',
    messagingSenderId: '359386672702',
    projectId: 'challenger-app-c941b',
    storageBucket: 'challenger-app-c941b.appspot.com',
    iosBundleId: 'kz.challengemaster.jihc.challengeMaster',
  );
}
